controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
not_found:
    path: /{wildcard}
    controller: App\Controller\DefaultController::notFound
    requirements:
        wildcard: ".+"